name = "DifferentiableTrajectoryOptimization"
uuid = "86fad55d-71c6-41a1-96ed-88d107dcd2ba"
authors = ["David Fridovich-Keil <dfk@utexas.edu>", "Forrest Laine <forrest.laine@vanderbilt.edu", "Lasse Peters <lasse.peters@mailbox.org>"]
version = "0.2.6"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
ChainRulesCore = "1"
ForwardDiff = "0.10"
Ipopt = "0.9, 1"
OSQP = "0.7, 0.8"
PATHSolver = "1.2"
Symbolics = "4, 5,6"
julia = "1.7"
